if(DEFINED ENV{SHIZUKU_KERNEL_PRELOAD_TOOLCHAIN}
   AND NOT SHIZUKU_KERNEL_PRELOAD_TOOLCHAIN)
  set(SHIZUKU_KERNEL_PRELOAD_TOOLCHAIN $ENV{SHIZUKU_KERNEL_PRELOAD_TOOLCHAIN})
endif()
if(EXISTS
   ${CMAKE_CURRENT_SOURCE_DIR}/toolchains/${SHIZUKU_KERNEL_PRELOAD_TOOLCHAIN})
  include(
    ${CMAKE_CURRENT_SOURCE_DIR}/toolchains/${SHIZUKU_KERNEL_PRELOAD_TOOLCHAIN})
else()
  message(
    "[warning] SHIZUKU_PRELOAD_TOOLCHAIN NOT FOUND. It maybe cause cmake configuration error."
  )
endif()
